USE ROLE ACCOUNTADMIN;

CREATE ROLE SNOWFLAKE_DEV_ROLE;

CREATE WAREHOUSE DEV_WH
  WAREHOUSE_SIZE = 'SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE;

  CREATE DATABASE SALES_DB;

CREATE SCHEMA SALES_DB.RAW_SCHEMA;
CREATE SCHEMA SALES_DB.PROCESSED_SCHEMA;
CREATE SCHEMA SALES_DB.LOG_SCHEMA;

GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT OPERATE ON WAREHOUSE DEV_WH TO ROLE SNOWFLAKE_DEV_ROLE;



GRANT USAGE ON DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT USAGE ON ALL SCHEMAS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT ALL PRIVILEGES ON ALL STAGES IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STAGES IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;


GRANT ALL PRIVILEGES ON ALL STREAMS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE STREAMS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT ALL PRIVILEGES ON ALL TASKS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT ALL PRIVILEGES ON FUTURE TASKS IN DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT ROLE SNOWFLAKE_DEV_ROLE TO USER GAJENDRASAINI;    

