CREATE OR REPLACE TABLE SALES_DB.LOG_SCHEMA.PIPELINE_LOG (
    LOG_ID NUMBER AUTOINCREMENT,
    PIPELINE_NAME STRING,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    ROWS_PROCESSED NUMBER,
    STATUS STRING,
    ERROR_MESSAGE STRING
);

select * from SALES_DB.LOG_SCHEMA.PIPELINE_LOG;

SHOW TABLES LIKE 'PIPELINE_LOG' IN SCHEMA SALES_DB.LOG_SCHEMA;

CREATE OR REPLACE ROW ACCESS POLICY REGION_POLICY
AS (region STRING)
RETURNS BOOLEAN ->
    CASE
        WHEN CURRENT_ROLE() = 'SNOWFLAKE_DEV_ROLE' THEN TRUE
        WHEN CURRENT_ROLE() = 'PUBLIC' AND region = 'Ege' THEN TRUE
        ELSE FALSE
    END;

    ALTER TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN
ADD ROW ACCESS POLICY REGION_POLICY ON (REGION);



CREATE OR REPLACE MASKING POLICY EMAIL_MASK
AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('SNOWFLAKE_DEV_ROLE') THEN val
        ELSE '***MASKED***'
    END;
    
    ALTER TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN
MODIFY COLUMN EMAIL SET MASKING POLICY EMAIL_MASK;

select * from SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN;--34999

GRANT USAGE ON DATABASE SALES_DB TO ROLE PUBLIC;
GRANT USAGE ON SCHEMA SALES_DB.PROCESSED_SCHEMA TO ROLE PUBLIC;
GRANT SELECT ON TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN TO ROLE PUBLIC;
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE PUBLIC;
USE ROLE PUBLIC;
SELECT * FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN;--5012

CREATE OR REPLACE DYNAMIC TABLE SALES_DB.RAW_SCHEMA.CUSTOMER_DYNAMIC
TARGET_LAG = '2 minutes'
WAREHOUSE = DEV_WH
AS
SELECT *
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN;

    ALTER TABLE SALES_DB.RAW_SCHEMA.CUSTOMER_DYNAMIC
MODIFY COLUMN EMAIL SET MASKING POLICY EMAIL_MASK;

SELECT * FROM SALES_DB.RAW_SCHEMA.CUSTOMER_DYNAMIC;

use role public;
select current_role();

SELECT SNOWFLAKE.CORTEX.SENTIMENT('I love Snowflake');

SHOW ORGANIZATION PARAMETERS LIKE 'ENABLE_CORTEX%';
use role accountadmin;
ALTER ACCOUNT SET ENABLE_CORTEX_CROSS_REGION_INFERENCE = TRUE;

SELECT SNOWFLAKE.CORTEX.SENTIMENT('Snowflake is powerful');

ALTER ACCOUNT SET CORTEX_ENABLED_CROSS_REGION = 'AWS_US';