CREATE OR REPLACE TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES AS
SELECT
    USER_ID,
    STATUS,
    DATEDIFF('YEAR', BIRTH_DATE, CURRENT_DATE()) AS AGE,
    GENDER,
    REGION
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN
WHERE STATUS IS NOT NULL
AND BIRTH_DATE IS NOT NULL;

select * from SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES;

CREATE OR REPLACE TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES AS
SELECT
    USER_ID,
    CASE 
        WHEN DATEDIFF('YEAR', BIRTH_DATE, CURRENT_DATE()) > 60 THEN 0
        ELSE 1
    END AS STATUS,
    DATEDIFF('YEAR', BIRTH_DATE, CURRENT_DATE()) AS AGE,
    GENDER,
    REGION
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN
WHERE BIRTH_DATE IS NOT NULL;

CREATE OR REPLACE STAGE SALES_DB.PROCESSED_SCHEMA.ML_STAGE;

SELECT
    USER_ID,
    SALES_DB.PROCESSED_SCHEMA.PREDICT_CUSTOMER_STATUS(
        AGE,
        GENDER,
        REGION
    ) AS PREDICTED_PROBABILITY
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES
LIMIT 10;

SELECT DISTINCT STATUS
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN;


SELECT
    USER_ID,
    CASE
        WHEN SALES_DB.PROCESSED_SCHEMA.PREDICT_CUSTOMER_STATUS(
            AGE, GENDER, REGION
        ) > 0.5 THEN 'LIKELY_ACTIVE'
        ELSE 'LIKELY_INACTIVE'
    END AS PREDICTION
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES;

CREATE OR REPLACE TABLE SALES_DB.PROCESSED_SCHEMA.CUSTOMER_PREDICTIONS AS
SELECT
    USER_ID,
    SALES_DB.PROCESSED_SCHEMA.PREDICT_CUSTOMER_STATUS(
        AGE,
        GENDER,
        REGION
    ) AS PROBABILITY,
    CURRENT_TIMESTAMP() AS SCORED_AT
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_ML_FEATURES;

SELECT USER_ID, PROBABILITY
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_PREDICTIONS
LIMIT 10;