
use role snowflake_dev_role;

CREATE OR REPLACE TABLE PROCESSED_SCHEMA.CUSTOMER_CLEAN (
    USER_ID        NUMBER,
    EMAIL        STRING,
    NAME           STRING,
    STATUS         NUMBER,
    GENDER         STRING,
    BIRTH_DATE     DATE,
    REGION         STRING,
    CITY           STRING,
    TOWN           STRING,
    DISTRICT       STRING,
    ADDRESS        STRING,
    LOAD_TS        TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

INSERT INTO PROCESSED_SCHEMA.CUSTOMER_CLEAN
(
    USER_ID,
    EMAIL,
    NAME,
    STATUS,
    GENDER,
    BIRTH_DATE,
    REGION,
    CITY,
    TOWN,
    DISTRICT,
    ADDRESS
)
SELECT
    TRY_TO_NUMBER(USERID),
    TRIM(USERNAME_),
    TRIM(NAMESURNAME),
    TRY_TO_NUMBER(STATUS_),
    TRIM(USERGENDER),
    TRY_TO_DATE(USERBIRTHDATE),
    TRIM(REGION),
    TRIM(CITY),
    TRIM(TOWN),
    TRIM(DISTRICT),
    TRIM(ADDRESSTEXT)
FROM RAW_SCHEMA.CUSTOMER_RAW
WHERE USERID IS NOT NULL;


select * from customer_clean;

