USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE STORAGE INTEGRATION azure_int
TYPE = EXTERNAL_STAGE
STORAGE_PROVIDER = AZURE
ENABLED = TRUE
AZURE_TENANT_ID = '8e9177d9-1cd5-4aef-8d65-1f33deaaeadd'
STORAGE_ALLOWED_LOCATIONS = ('azure://snowstreamlearn.blob.core.windows.net/raw/customer/');

DESC INTEGRATION azure_int;

USE ROLE SNOWFLAKE_DEV_ROLE;

CREATE OR REPLACE FILE FORMAT sales_db.raw_schema.CSV_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = ','
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL', 'null');

CREATE OR REPLACE STAGE raw_schema.customer_stage
URL = 'azure://snowstreamlearn.blob.core.windows.net/raw/customer/'
STORAGE_INTEGRATION = azure_int
FILE_FORMAT = RAW_SCHEMA.CSV_FORMAT;

list @customer_stage;

CREATE OR REPLACE FILE FORMAT RAW_SCHEMA.DEBUG_PIPE_FORMAT
TYPE = 'CSV'
FIELD_DELIMITER = '|'
SKIP_HEADER = 0;

SELECT $1
FROM @RAW_SCHEMA.CUSTOMER_STAGE
(FILE_FORMAT => 'RAW_SCHEMA.DEBUG_PIPE_FORMAT')
LIMIT 1;

CREATE OR REPLACE TABLE RAW_SCHEMA.CUSTOMER_RAW (
    USERID        STRING,
    USERNAME_     STRING,
    NAMESURNAME   STRING,
    STATUS_       STRING,
    USERGENDER    STRING,
    USERBIRTHDATE STRING,
    REGION        STRING,
    CITY          STRING,
    TOWN          STRING,
    DISTRICT      STRING,
    ADDRESSTEXT   STRING
);

COPY INTO RAW_SCHEMA.CUSTOMER_RAW
FROM @RAW_SCHEMA.CUSTOMER_STAGE
FILE_FORMAT = (FORMAT_NAME = 'RAW_SCHEMA.CSV_FORMAT')
FILES = ('customers1.csv');

SELECT COUNT(*) FROM RAW_SCHEMA.CUSTOMER_RAW;

select * from customer_raw limit 1;
