USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE NOTIFICATION INTEGRATION azure_queue_int
TYPE = QUEUE
ENABLED = TRUE
NOTIFICATION_PROVIDER = AZURE_STORAGE_QUEUE
AZURE_STORAGE_QUEUE_PRIMARY_URI = 
'https://snowstreamlearn.queue.core.windows.net/customer-que'
AZURE_TENANT_ID = '8e9177d9-1cd5-4aef-8d65-1f33deaaeadd';

DESC NOTIFICATION INTEGRATION azure_queue_int;--sef7cxsnowflakepacint_1771740054904

USE ROLE SNOWFLAKE_DEV_ROLE;

USE SECONDARY ROLES NONE;
USE ROLE PUBLIC;

SELECT CURRENT_ROLE();


SELECT EMAIL, REGION
FROM SALES_DB.PROCESSED_SCHEMA.CUSTOMER_CLEAN
LIMIT 5;



CREATE OR REPLACE PIPE RAW_SCHEMA.CUSTOMER_PIPE
AUTO_INGEST = TRUE
INTEGRATION = azure_queue_int
AS
COPY INTO RAW_SCHEMA.CUSTOMER_RAW
FROM @RAW_SCHEMA.CUSTOMER_STAGE
FILE_FORMAT = (FORMAT_NAME = 'RAW_SCHEMA.CSV_FORMAT');

USE ROLE ACCOUNTADMIN;
GRANT USAGE ON INTEGRATION AZURE_INT TO ROLE SNOWFLAKE_DEV_ROLE;
GRANT USAGE ON INTEGRATION AZURE_QUEUE_INT TO ROLE SNOWFLAKE_DEV_ROLE;

SELECT SYSTEM$PIPE_STATUS('RAW_SCHEMA.CUSTOMER_PIPE');


DESC PIPE RAW_SCHEMA.CUSTOMER_PIPE;

DESC NOTIFICATION INTEGRATION azure_queue_int;


SELECT COUNT(*) FROM RAW_SCHEMA.CUSTOMER_RAW;

select * from RAW_SCHEMA.CUSTOMER_RAW;


USE ROLE ACCOUNTADMIN;
GRANT USAGE ON DATABASE SALES_DB TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT USAGE ON SCHEMA SALES_DB.RAW_SCHEMA 
TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT SELECT ON TABLE SALES_DB.RAW_SCHEMA.CUSTOMER_RAW
TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT CREATE STREAM ON SCHEMA SALES_DB.RAW_SCHEMA
TO ROLE SNOWFLAKE_DEV_ROLE;



GRANT CREATE STREAM ON SCHEMA SALES_DB.RAW_SCHEMA 
TO ROLE SNOWFLAKE_DEV_ROLE;

USE SECONDARY ROLES NONE;

use role snowflake_dev_role;


CREATE OR REPLACE STREAM SALES_DB.RAW_SCHEMA.CUSTOMER_STREAM
ON TABLE SALES_DB.RAW_SCHEMA.CUSTOMER_RAW;

SELECT SYSTEM$PIPE_STATUS('RAW_SCHEMA.CUSTOMER_PIPE');

SELECT METADATA$ACTION,
       METADATA$ISUPDATE,
       USERID
FROM RAW_SCHEMA.CUSTOMER_STREAM;


