USE ROLE SNOWFLAKE_DEV_ROLE;

CREATE OR REPLACE TASK SALES_DB.RAW_SCHEMA.CUSTOMER_TASK
WAREHOUSE = DEV_WH
SCHEDULE = '1 MINUTE'
WHEN SYSTEM$STREAM_HAS_DATA('RAW_SCHEMA.CUSTOMER_STREAM')
AS
CALL SALES_DB.RAW_SCHEMA.PROCESS_CUSTOMER_STREAM();

ALTER TASK CUSTOMER_TASK RESUME;

SELECT *
FROM TABLE(
  INFORMATION_SCHEMA.TASK_HISTORY(
    TASK_NAME => 'CUSTOMER_TASK'
  )
);


USE ROLE ACCOUNTADMIN;
GRANT IMPORTED PRIVILEGES 
ON DATABASE SNOWFLAKE 
TO ROLE SNOWFLAKE_DEV_ROLE;

GRANT EXECUTE TASK ON ACCOUNT TO ROLE SNOWFLAKE_DEV_ROLE;
USE ROLE SNOWFLAKE_DEV_ROLE;
ALTER TASK CUSTOMER_TASK SUSPEND;
ALTER TASK CUSTOMER_TASK RESUME;

SHOW GRANTS TO ROLE SNOWFLAKE_DEV_ROLE;

USE ROLE SNOWFLAKE_DEV_ROLE;SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    RESULT_LIMIT => 5
));
SHOW TASKS IN SCHEMA SALES_DB.RAW_SCHEMA;

ALTER TASK SALES_DB.RAW_SCHEMA.CUSTOMER_TASK RESUME;
SHOW TASKS LIKE 'CUSTOMER_TASK' IN SCHEMA SALES_DB.RAW_SCHEMA;
SELECT SYSTEM$STREAM_HAS_DATA('SALES_DB.RAW_SCHEMA.CUSTOMER_STREAM');

ALTER TASK SALES_DB.RAW_SCHEMA.CUSTOMER_TASK SUSPEND;
ALTER TASK SALES_DB.RAW_SCHEMA.CUSTOMER_TASK RESUME;

SHOW TASKS LIKE 'CUSTOMER_TASK' IN SCHEMA SALES_DB.RAW_SCHEMA;

SELECT *
FROM TABLE(INFORMATION_SCHEMA.TASK_HISTORY(
    RESULT_LIMIT => 5
));